#! /usr/bin/env python

from argparse import ArgumentParser
from datetime import datetime

from git import Repo

if __name__ == "__main__":
    parser = ArgumentParser()

    parser.add_argument("--add", action="store_true")
    parser.add_argument("--clean", action="store_true")
    parser.add_argument("--commit", action="store_true")
    parser.add_argument("--pull", action="store_true")
    parser.add_argument("--push", action="store_true")

    flags = parser.parse_args()

    now = datetime.now().strftime("%Y-%m-%d-%H-%M-%S")

    message = f"""
    🤖 RenTrueWang commits at {now}

    Beep Boop, I'm a bot. I'm not the real author of this repo. @rentruewang is the one who wrote the code and commits when he sees fits.

    If you feel rather strongly for @rentruewang to write a more professional message, clarify things, or just want to fix things, please reach out to him or comment on the part where you dislike. He will be getting a notification everytime you do so. Hopefully he listens to your suggestions! Beep Boop, message over!

    I am a bot, and this action is performed automatically. The source code can be found at https://github.com/rentruewang/tmp/github
    """.strip()

    repo = Repo(".")

    if flags.clean:
        repo.git.clean("-fdX")

    if flags.pull:
        repo.remotes.origin.pull()

    if flags.add:
        repo.git.add(".")

    if flags.commit:
        repo.index.commit(message)

    if flags.push:
        repo.remotes.origin.push()
