/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package route;

public class App {
    public static void main(String[] args) {
        var loader = new Loader();
        var router = new Router();
    }
}
