/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package route;

import java.util.ArrayList;

public class App {
    public static void main(String[] args) {
        var nets = new ArrayList<Net>();
        var router = new Router(nets);
    }
}
